# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-17 16:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(help_text=b'Indentificacion de la persona, debe ser unica', max_length=20, unique=True)),
                ('sede', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[(b'Usuario', b'Usuario'), (b'Administrador', b'Administrador')], default=b'Usuario', max_length=50)),
                ('imagen', models.ImageField(upload_to=b'imagenes/persona')),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persona', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['identificacion'],
                'verbose_name_plural': 'Personas',
            },
        ),
    ]
